### ISSUE TITLE
Problem with inspire on 3.3?

### ISSUE THREAD

**Issue by mkpelletier** [moodlehq/moodle-tool_inspire#2]
Hello All,

After running the evaluation tool none of my courses open.  Instead I get this error in my webserver log:

"PHP message: PHP Fatal error: Using $this when not in object context in /var/www/moodle/admin/tool/inspire/classes/manager.php on line 68" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: dev.server.com, request: "GET /course/view.php?id=1306 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "dev.server.com", referrer: "https://dev.server.com/course/index.php?categoryid=176"

Any idea on what is wrong here?

**Comment by dmonllao** [comment]
Wow yes, this is horrible, it will be fixed tomorrow morning (GMT +8) This is due to a last minute change I included. Thanks for the report!

By the way, it seems that you are using php 5.6, php 7.0 is a requirement for the php machine learning library we use. You can still use the python predictor although you would need to install it.

**Comment by mkpelletier** [comment]
Hi. Thanks for the response.  I had switched to the python predictor because of the additional function.  In any case, you are right that I am using 5.6.

**Comment by dmonllao** [comment]
Hi Mathieu,

This should be fixed now (https://github.com/moodlehq/moodle-tool_inspire/commit/f2cb5644744da9977c7f464ce820dbf3ec4249cc) thanks for reporting the issue, don't hesitate to report further problems you find. Closing
